export const PAYMENT_METHODS = ['CASH', 'TRANSFER', 'CREDIT_CARD', 'DEBIT_CARD'];
export const PAYMENT_TYPES = ['DEPOSIT', 'FINAL_PAYMENT', 'FULL_PAYMENT'];
export const PAYMENT_STATUS = ['PENDING', 'PARTIAL', 'COMPLETED', 'REFUNDED'];
